In [3]:
#Dependencies
import csv
import matplotlib.pyplot as plt
import requests
import pandas as pd
from config import api_key
import json

In [4]:
cities_pd = pd.read_csv('worldcities.csv')

In [5]:
random_cities = cities_pd.sample(n=500)
new_cities = random_cities.reset_index()
new_cities['City'].value_counts()

weare                         1
prieska                       1
torello                       1
lichtenvoorde                 1
costeiu                       1
swedru                        1
ilama                         1
enns                          1
macamic                       1
maruko                        1
morong                        1
jucas                         1
ntoum                         1
doische                       1
sukhoverkovo                  1
homagama                      1
ilam                          1
cedar park                    1
castiglione delle stiviere    1
mizur                         1
grosse ile                    1
valpoi                        1
bancal                        1
socastee                      1
charta                        1
aroeiras                      1
kartarpur                     1
des moines                    1
livramento                    1
gurinhem                      1
                             ..
zacatepec                     1
matnog                        1
racoviteni                    1
hamilton                      1
pereira barreto               1
cikupa                        1
richards bay                  1
mandi bahauddin               1
banderilla                    1
martinez                      1
sabla                         1
lengshuijiang                 1
orissaare                     1
sabancuy                      1
shache                        1
velesin                       1
salinas                       1
deoli                         1
abis                          1
lagdo                         1
kamenice nad lipou            1
otradnoye                     1
san vicente                   1
lupsa                         1
ivanteyevka                   1
kepno                         1
kinamayan                     1
kosgi                         1
biel                          1
forbes                        1
Name: City, Length: 500, dtype: int64

In [9]:
new_cities['Temperature'] =''
new_cities['Wind'] = ''
new_cities['Humidity'] = ''
new_cities['Cloudiness'] = ''
new_cities.head()

,index,Country,City,Latitude,Longitude,Temperature,Wind,Humidity,Cloudiness
0,26923,ph,abis,9.717300,122.943800,,,,
1,33491,ro,malu mare,44.233333,23.866667,,,,
2,42399,us,lompoc,34.639167,-120.456944,,,,
3,5766,cm,kumbo,6.200000,10.666667,,,,
4,41116,tz,vikindu,-6.983333,39.283333,,,,

In [7]:
url = "http://api.openweathermap.org/data/2.5/weather?"
units = "imperial"

In [12]:
# Loop through the new_cities and run a temp/wind/humidity/cloudiness search for each city

row_count = 0

for index, row in new_cities.iterrows():
    query_url = f"{url}appid={api_key}&units={units}&q="

    city = row['City']
    
    print("Now retrieving city #%s: %s" %
          (row_count, new_cities.loc[index]["City"]))
    row_count += 1

    # make request, print url
    city_response = requests.get(query_url + city)
    print(city_response.url)
    # convert to json
    city_reponse = city_response.json()

    new_cities.set_value(index, "Temperature", city_response['main']['temp_max'])
    new_cities.set_value(index, "Wind", city_response['wind']['speed'])
    new_cities.set_value(index, "Humidity", city_response['main']['humidity'])
    new_cities.set_value(index, "Cloudiness", city_response['clouds']['all'])

Now retrieving city #0: abis
http://api.openweathermap.org/data/2.5/weather?appid=25bc90a1196e6f153eece0bc0b0fc9eb&units=imperial&q=abis

TypeError: 'Response' object is not subscriptable

In [ ]:
# Build a scatter plot for each data type
plt.scatter(new_cities['Latitude'],
            new_cities["Temperature"],
            edgecolor="black", linewidths=1, marker="o",
            alpha=0.8)

# Incorporate the other graph properties
plt.title("City Latitude vs. Max Temp")
plt.ylabel("Max Temperature (f)")
plt.xlabel("Latitude")
plt.grid(True)
#plt.xlim([-2.5, 202])
#plt.ylim([-2.5, 110000])

# Save the figure
plt.savefig("output_analysis/Temp_Latitude.png")

# Show plot
plt.show()

In [ ]:
# Build a scatter plot for each data type
plt.scatter(new_cities['Latitude'],
            new_cities["Wind"],
            edgecolor="black", linewidths=1, marker="o",
            alpha=0.8)

# Incorporate the other graph properties
plt.title("City Latitude vs. Wind Speed")
plt.ylabel("Wind Speed (mph)")
plt.xlabel("Latitude")
plt.grid(True)
#plt.xlim([-2.5, 202])
#plt.ylim([-2.5, 110000])

# Save the figure
plt.savefig("output_analysis/Wind_Latitude.png")

# Show plot
plt.show()

In [ ]:
# Build a scatter plot for each data type
plt.scatter(new_cities['Latitude'],
            new_cities["Humidity"],
            edgecolor="black", linewidths=1, marker="o",
            alpha=0.8)

# Incorporate the other graph properties
plt.title("City Latitude vs. Humidity (%)")
plt.ylabel("Humidity (%)")
plt.xlabel("Latitude")
plt.grid(True)
#plt.xlim([-2.5, 202])
#plt.ylim([-2.5, 110000])

# Save the figure
plt.savefig("output_analysis/Humidity_Latitude.png")

# Show plot
plt.show()

In [ ]:
# Build a scatter plot for each data type
plt.scatter(new_cities['Latitude'],
            new_cities["Cloudiness"],
            edgecolor="black", linewidths=1, marker="o",
            alpha=0.8)

# Incorporate the other graph properties
plt.title("City Latitude vs. Cloudiness (%)")
plt.ylabel("Cloudiness (%)")
plt.xlabel("Latitude")
plt.grid(True)
#plt.xlim([-2.5, 202])
#plt.ylim([-2.5, 110000])

# Save the figure
plt.savefig("output_analysis/Cloudiness_Latitude.png")

# Show plot
plt.show()